FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80

ENV ASPNETCORE_URLS=http://+:80

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["YaqeenApi.csproj", "./"]
RUN dotnet restore "YaqeenApi.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "YaqeenApi.csproj" -c Debug -o /app/build

FROM build AS publish
RUN dotnet publish "YaqeenApi.csproj" -c Debug -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

ENV ASPNETCORE_ENVIRONMENT=Development
ENV LOG_LEVEL=Debug

ENTRYPOINT ["dotnet", "YaqeenApi.dll"]
